spring.application.name=FarmerAiAssistent
#spring.application.name=plantcare

# ==============================
# WEATHER API
# ==============================

weather.api.url=https://api.weatherapi.com/v1/current.json
weather.api.forecast.url=https://api.weatherapi.com/v1/forecast.json
weather.api.key=a6db28d19326401984590038261804


# ==============================
# GEMINI CHAT API
# ==============================

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/interactions
#gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models
gemini.api.key=AQ.Ab8RN6Kv62GW4uhw3d80N1LC5yVDYqn4ELU9JI8swN8jbWmU7g


# ==============================
# MARKET API
# ==============================

#market.api.url=https://api.ceda.ashoka.edu.in
#market.api.key=4862eb97f8e77bbf7eb9cc5dcc713f8474a65cfc908c65cc0773bfc35937567d


# ==============================
# DISEASE DETECTION API
# ==============================

disease.api.url=https://crop.kindwise.com/api/v1/identification
disease.api.key=yLfaS6HJNZqVVhFFGlhurY3vQznPyyvYYyGInnXolTT3pkXKNU
